config/routes.rb
Rails.application.routes.draw do
  devise_for :users , controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}  
  
  namespace :admin do
   root  to: 'dashboard#index'
   resources :structures
  end
  
  namespace :api do
    namespace :v1 do
      resources :structures
      resources :posts
    end
  end


    
  get 'posts/index'

  get 'posts/show'

  get 'contacts/index'

  get 'about/index'

  get 'home/index'

  get 'account/index'

  get 'what_see/index'
  
  root "home#index"

  resources :posts do
    resources :comments
  end
  resources :structures, only: [:index, :show]



  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/structure.rb
class Structure < ApplicationRecord
  validates :name, :description, presence: true

  has_one :address, :as => :addressable, inverse_of: :addressable
  accepts_nested_attributes_for :address, allow_destroy: true
  has_one :seo_tag, :as => :seo_polymorphic, inverse_of: :seo_polymorphic
  accepts_nested_attributes_for :seo_tag, allow_destroy: true
 end

app/controllers/admin/structures_controller.rb
class Admin::StructuresController < Admin::BaseController
  before_action :set_structure, only: [:show, :edit, :update, :destroy]

  # GET /structures
  # GET /structures.json
  def index
    @structures = Structure.all
  end

  # GET /structures/1
  # GET /structures/1.json
  def show
  end

  # GET /structures/new
  def new
    @structure = Structure.new
    @structure.build_address
    @structure.build_seo_tag
  end

  # GET /structures/1/edit
  def edit
  end

  # POST /structures
  # POST /structures.json
  def create
    @structure = Structure.new(structure_params)

    respond_to do |format|
      if @structure.save
        format.html { redirect_to @structure, notice: 'Structure was successfully created.' }
        format.json { render :show, status: :created, location: @structure }
      else
        format.html { render :new }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /structures/1
  # PATCH/PUT /structures/1.json
  def update
    respond_to do |format|
      if @structure.update(structure_params)
        format.html { redirect_to @structure, notice: 'Structure was successfully updated.' }
        format.json { render :show, status: :ok, location: @structure }
      else
        format.html { render :edit }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /structures/1
  # DELETE /structures/1.json
  def destroy
    @structure.destroy
    respond_to do |format|
      format.html { redirect_to admin_structures_url, notice: 'Structure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_structure
      @structure = Structure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def structure_params
      params.require(:structure).permit(:name, :description, address_attributes: [:id, :street, :street_number, :city, :province, :zipcode, :country, :latitude, :longitude, :addressable_type, :addressable_id, :_destroy], seo_tag_attributes: [:id, :tag_title, :tag_description, :seo_polymorphic_type, :seo_polymorphic_id, :_destroy])
    end
end

app/controllers/api/v1/structures_controller.rb
class Api::V1::StructuresController < ApplicationController
  before_action :set_structure,  only: [:show]


  def index
    render json: Structure.all
  end

  def show
    render json: @structure
  end

  private

  def set_structure
    @structure = Structure.find(params[:id])
  end

end

app/controllers/structures_controller.rb
class StructuresController < ApplicationController
  before_action :set_structure, only: [:show, :edit, :update, :destroy]

  # GET /structures
  # GET /structures.json
  def index
    @structures = Structure.all
  end

  # GET /structures/1
  # GET /structures/1.json
  def show
  end

  # GET /structures/new
  def new
    @structure = Structure.new
    @structure.build_address
  end

  # GET /structures/1/edit
  def edit
  end

  # POST /structures
  # POST /structures.json
  def create
    @structure = Structure.new(structure_params)

    respond_to do |format|
      if @structure.save
        format.html { redirect_to @structure, notice: 'Structure was successfully created.' }
        format.json { render :show, status: :created, location: @structure }
      else
        format.html { render :new }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /structures/1
  # PATCH/PUT /structures/1.json
  def update
    respond_to do |format|
      if @structure.update(structure_params)
        format.html { redirect_to @structure, notice: 'Structure was successfully updated.' }
        format.json { render :show, status: :ok, location: @structure }
      else
        format.html { render :edit }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /structures/1
  # DELETE /structures/1.json
  def destroy
    @structure.destroy
    respond_to do |format|
      format.html { redirect_to structures_url, notice: 'Structure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_structure
      @structure = Structure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def structure_params
      params.require(:structure).permit(:name, :description, address_attributes: [:street, :street_number, :city, :province, :zipcode, :country, :latitude, :longitude, :_destroy])
    end
end

app/helpers/admin/structures_helper.rb
module Admin::StructuresHelper
end

app/helpers/structures_helper.rb
module StructuresHelper
end

app/views/admin/structures/_form.html.erb
<%= simple_form_for [:admin, structure] do |form|%>
   
  <div class="card mb-4">
    <h5 class="card-header bg-primary"> Dati azienda: </h5> 
    <div class="card-body">
      <%= form.input :name%>
      <%= form.input :description%>
    </div>
  </div>

  <%= form.simple_fields_for :address do |address|%>
    <div class="card mb-4">
      <h5 class="card-header bg-primary"> Indirizzo azienda: </h5>
      <div class="card-body">

        <div class="form-row">
          <div class="col-md-4">
            <%= address.input :city%>
          </div>
          <div class="col-md-4">
            <%= address.input :province%>
          </div>
          <div class="col-md-4">
            <%= address.input :country%>
          </div>
        </div>
        <div class="form-row">
          <div class="col-md-6">
            <%= address.input :street%>
          </div>
          <div class="col-md-3">
            <%= address.input :street_number%>
          </div>
          <div class="col-md-3">
            <%= address.input :zipcode%>
          </div>
        </div>

      </div>
    </div>
  <%end%> 
  
  <%= form.simple_fields_for :seo_tag do |seo|%>
    <div class="card mb-4">
      <h5 class="card-header bg-primary"> Seo: </h5>
      <div class="card-body">
        <%= seo.input :tag_title %>
        <%= seo.input :tag_description%>
      </div>
    </div>
   <%end%>
  
  <%= form.button :submit, class:"btn btn-primary"%>
<%end%>

app/views/admin/structures/edit.html.erb
<h1 class="my-4 text-left text-lg-left"> Edit Structure</h1>
<div class="row">
  <div class="col-md-12 mb-4">
    <%= render 'form', structure: @structure%>
    <hr>
  </div>
  <div class="col-md-12 text-center mb-4">
    <%= link_to fa_icon("eye ") + " " + @structure.name, [:admin, @structure], class: "btn btn-secondary"%> | 
    <%= link_to fa_icon("home") + " Structures", admin_structures_path, class: "btn btn-info"%>
  </div>
</div>

app/views/admin/structures/index.html.erb
<h1 class="my-4 text-center text-lg-left">Structures</h1>
<div class="row text-center text-lg-left">
  <div class="col-md-12 mb-4">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col"> # </th>
          <th scope="col"> Name</th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @structures.each do |structure|%>
          <tr>
            <th scope="row"><%= structure.id%></th>
            <td><%= link_to structure.name, admin_structure_path(structure) %></td>
            <td class="text-right"><%= link_to fa_icon("pencil") + " Edit", edit_admin_structure_path(structure), class: "btn btn-primary"%></td>
            <td class="text-right"><%= link_to fa_icon("trash") + " Destroy", admin_structure_path(structure), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"%></td>
          </tr>
        <%end%>
      </tbody>
    </table>      
  <%= link_to fa_icon("plus") + " New structure", new_admin_structure_path, class: "btn btn-success"%>
  </div>
</div>

app/views/admin/structures/new.html.erb
<h1 class="my-4 text-center text-lg-left">New Structure</h1>
<div class="row">
  <div class="col-md-12 mb-4">
    <%= render 'form', structure: @structure%>
    <hr>
  </div>
  
  <div class="col-md-12 text-center mb-4">
  <%= link_to fa_icon("home") + ' Structures', admin_structures_path, class: "btn btn-info"%> 
  </div>
</div>

app/views/admin/structures/show.html.erb
  <!-- Page Heading/Breadcrumbs -->
      <h1 class="mt-4 mb-3"><%= @structure.name%>
        <small>(categoria merceologica)</small>
      </h1>

      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="/admin">Dashboard</a>
        </li>
        <li class="breadcrumb-item"><%= link_to "Structures", admin_structures_path%></li>
        <li class="breadcrumb-item active"><%= @structure.name%></li>
      </ol>

      <!-- Portfolio Item Row -->
      <div class="row">

        <div class="col-md-8">
          <img class="img-fluid" src="http://placehold.it/750x500" alt="">
        </div>

        <div class="col-md-4">
          <h3 class="my-3">Dettagli</h3>
          <p><%= @structure.description%></p>
          <h3 class="my-3">Project Details</h3>
          <ul>
            <li>Lorem Ipsum</li>
            <li>Dolor Sit Amet</li>
            <li>Consectetur</li>
            <li>Adipiscing Elit</li>
          </ul>
        </div>

      </div>
      <!-- /.row -->

      <!-- Related Projects Row -->
      <h3 class="my-4">Related Projects</h3>

      <div class="row">

        <div class="col-md-3 col-sm-6 mb-4">
          <a href="#">
            <img class="img-fluid" src="http://placehold.it/500x300" alt="">
          </a>
        </div>

        <div class="col-md-3 col-sm-6 mb-4">
          <a href="#">
            <img class="img-fluid" src="http://placehold.it/500x300" alt="">
          </a>
        </div>

        <div class="col-md-3 col-sm-6 mb-4">
          <a href="#">
            <img class="img-fluid" src="http://placehold.it/500x300" alt="">
          </a>
        </div>

        <div class="col-md-3 col-sm-6 mb-4">
          <a href="#">
            <img class="img-fluid" src="http://placehold.it/500x300" alt="">
          </a>
        </div>

      </div>
      <!-- /.row -->


      <div class="row">
        <div class="col-md-4 col-sm-6 mb-4">
          <%= link_to fa_icon("pencil") + ' Edit', edit_admin_structure_path(@structure), class: "btn btn-primary"%>
          <%= link_to fa_icon("trash") + ' Destroy', admin_structure_path(@structure), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger"%>
          <%= link_to fa_icon("home") + ' Structures', admin_structures_path, class: "btn btn-info"%>
        </div>
      </div>