config/routes.rb
Rails.application.routes.draw do
  devise_for :users , controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}  
  
  namespace :admin do
   root  to: 'dashboard#index'
   resources :structures
  end
  
  namespace :api do
    namespace :v1 do
      resources :structures
      resources :posts
    end
  end


    
  get 'posts/index'

  get 'posts/show'

  get 'contacts/index'

  get 'about/index'

  get 'home/index'

  get 'account/index'

  get 'what_see/index'
  
  root "home#index"

  resources :posts do
    resources :comments
  end
  resources :structures, only: [:index, :show]



  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/structure.rb
class Structure < ApplicationRecord
  validates :name, :description, presence: true

  has_one :address, :as => :addressable, inverse_of: :addressable
  accepts_nested_attributes_for :address, allow_destroy: true
  has_one :seo_tag, :as => :seo_polymorphic, inverse_of: :seo_polymorphic
  accepts_nested_attributes_for :seo_tag, allow_destroy: true
 end

app/controllers/admin/structures_controller.rb
class Admin::StructuresController < Admin::BaseController
  before_action :set_structure, only: [:show, :edit, :update, :destroy]

  # GET /structures
  # GET /structures.json
  def index
    @structures = Structure.all
  end

  # GET /structures/1
  # GET /structures/1.json
  def show
  end

  # GET /structures/new
  def new
    @structure = Structure.new
    @structure.build_address
    @structure.build_seo_tag
  end

  # GET /structures/1/edit
  def edit
  end

  # POST /structures
  # POST /structures.json
  def create
    @structure = Structure.new(structure_params)

    respond_to do |format|
      if @structure.save
        format.html { redirect_to @structure, notice: 'Structure was successfully created.' }
        format.json { render :show, status: :created, location: @structure }
      else
        format.html { render :new }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /structures/1
  # PATCH/PUT /structures/1.json
  def update
    respond_to do |format|
      if @structure.update(structure_params)
        format.html { redirect_to @structure, notice: 'Structure was successfully updated.' }
        format.json { render :show, status: :ok, location: @structure }
      else
        format.html { render :edit }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /structures/1
  # DELETE /structures/1.json
  def destroy
    @structure.destroy
    respond_to do |format|
      format.html { redirect_to admin_structures_url, notice: 'Structure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_structure
      @structure = Structure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def structure_params
      params.require(:structure).permit(:name, :description, address_attributes: [:id, :street, :street_number, :city, :province, :zipcode, :country, :latitude, :longitude, :addressable_type, :addressable_id, :_destroy], seo_tag_attributes: [:id, :tag_title, :tag_description, :seo_polymorphic_type, :seo_polymorphic_id, :_destroy])
    end
end

app/controllers/api/v1/structures_controller.rb
class Api::V1::StructuresController < ApplicationController
  before_action :set_structure,  only: [:show]


  def index
    render json: Structure.all
  end

  def show
    render json: @structure
  end

  private

  def set_structure
    @structure = Structure.find(params[:id])
  end

end

app/controllers/structures_controller.rb
class StructuresController < ApplicationController
  before_action :set_structure, only: [:show, :edit, :update, :destroy]

  # GET /structures
  # GET /structures.json
  def index
    @structures = Structure.all
  end

  # GET /structures/1
  # GET /structures/1.json
  def show
  end

  # GET /structures/new
  def new
    @structure = Structure.new
    @structure.build_address
  end

  # GET /structures/1/edit
  def edit
  end

  # POST /structures
  # POST /structures.json
  def create
    @structure = Structure.new(structure_params)

    respond_to do |format|
      if @structure.save
        format.html { redirect_to @structure, notice: 'Structure was successfully created.' }
        format.json { render :show, status: :created, location: @structure }
      else
        format.html { render :new }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /structures/1
  # PATCH/PUT /structures/1.json
  def update
    respond_to do |format|
      if @structure.update(structure_params)
        format.html { redirect_to @structure, notice: 'Structure was successfully updated.' }
        format.json { render :show, status: :ok, location: @structure }
      else
        format.html { render :edit }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /structures/1
  # DELETE /structures/1.json
  def destroy
    @structure.destroy
    respond_to do |format|
      format.html { redirect_to structures_url, notice: 'Structure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_structure
      @structure = Structure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def structure_params
      params.require(:structure).permit(:name, :description, address_attributes: [:street, :street_number, :city, :province, :zipcode, :country, :latitude, :longitude, :_destroy])
    end
end

app/helpers/admin/structures_helper.rb
module Admin::StructuresHelper
end

app/helpers/structures_helper.rb
module StructuresHelper
end

app/views/structures/_form.html.erb
<!--<#%= form_with(model: structure, local: true) do |form| %>-->
  <%= simple_form_for structure do |form|%>
  <% if structure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(structure.errors.count, "error") %> prohibited this structure from being saved:</h2>

      <ul>
      <% structure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.input :name%>
  </div>

  <div class="field">
    <%= form.input :description%>
  </div>

  
  <hr>




  <div id="locationField">
    <% if @structure.new_record? %>
      <div class="form-group">
        <input id="autocomplete" placeholder="Enter your address" onFocus="geolocate()" type="text" required class="form-control" ></input>
      </div>
  <%else%>
    <input id="autocomplete" placeholder="Enter your address" onFocus="geolocate()" type="text"></input>
  <%end%>
  </div>
  <hr>
  


  <table id="address">
      <tr>
        <td class="label">Street address</td>
        <td class="slimField">
          <%= form.input :street_number, class:"field", id:"street_number", disabled:"true"%>
        </td>
        <td class="wideField" colspan="2">  
          <%= form.input :street, class:"field", id:"route", disabled:"true"%>
        </td>
      </tr>
      <tr>
        <td class="label">City</td>
        <td class="wideField" colspan="3">
          <%= form.input :city, class:"field", id:"locality", disabled:"true"%>
        </td>
      </tr>
      <tr>
        <td class="label">Province</td>
        <td class="slimField">
          <%= form.input :province, class:"field", id:"administrative_area_level_1", disabled:"true"%>
        </td>

        <td class="label">Zip code</td>
        <td class="wideField">
          <%= form.input :zipcode, class:"field", id:"postal_code", disabled:"true"%>
        </td>
      </tr>
      <tr>
        <td class="label">Country</td>
        <td class="wideField" colspan="3">
          <%= form.input :country, class:"field", id:"country", disabled:"true"%>
        </td>
      </tr>
    </table>


    



  <div class="actions">
    <%= form.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>




<script>
      // This example displays an address form, using the autocomplete feature
      // of the Google Places API to help users fill in the information.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var placeSearch, autocomplete;
      var componentForm = {
        street_number: 'short_name',
        route: 'long_name',
        locality: 'long_name',
        administrative_area_level_1: 'short_name',
        country: 'long_name',
        postal_code: 'short_name'
      };

      function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
        autocomplete = new google.maps.places.Autocomplete(
            /** @type {!HTMLInputElement} */(document.getElementById('autocomplete')),
            {types: ['geocode']});

        autocomplete.setComponentRestrictions(
            {'country': ['it']});

        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
        autocomplete.addListener('place_changed', fillInAddress);
      }

      function fillInAddress() {
        // Get the place details from the autocomplete object.
        var place = autocomplete.getPlace();

        for (var component in componentForm) {
          document.getElementById(component).value = '';
          document.getElementById(component).disabled = false;
        }

        // Get each component of the address from the place details
        // and fill the corresponding field on the form.
        for (var i = 0; i < place.address_components.length; i++) {
          var addressType = place.address_components[i].types[0];
          if (componentForm[addressType]) {
            var val = place.address_components[i][componentForm[addressType]];
            document.getElementById(addressType).value = val;
          }
        }
      }

      // Bias the autocomplete object to the user's geographical location,
      // as supplied by the browser's 'navigator.geolocation' object.
      function geolocate() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var geolocation = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            var circle = new google.maps.Circle({
              center: geolocation,
              radius: position.coords.accuracy
            });
            autocomplete.setBounds(circle.getBounds());
          });
        }
      }
      </script>


<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDi1llQEL98mof5OiynESOraX2piDuo_EM&libraries=places&callback=initAutocomplete"
        async defer></script>

app/views/structures/edit.html.erb
<h1>Editing Structure</h1>

<%= render 'form', structure: @structure %>

<%= link_to 'Show', @structure %> |
<%= link_to 'Back', structures_path %>

app/views/structures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Structures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Street</th>
      <th>Street number</th>
      <th>City</th>
      <th>Province</th>
      <th>Zipcode</th>
      <th>Country</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @structures.each do |structure| %>
      <tr>
        <td><%= structure.name %></td>
        <td><%= structure.description %></td>
        <%if structure.address.present?%>
          <td><%= structure.address.street %></td>
          <td><%= structure.address.street_number %></td>
          <td><%= structure.address.city %></td>
          <td><%= structure.address.province %></td>
          <td><%= structure.address.zipcode %></td>
          <td><%= structure.address.country %></td>
          <td><%= structure.address.latitude %></td>
          <td><%= structure.address.longitude %></td>
        <%end%>
        <td><%= link_to 'Show', structure %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/structures/new.html.erb
<h1>New Structure</h1>

<%= render 'form', structure: @structure %>

<%= link_to 'Back', structures_path %>

app/views/structures/show.html.erb
<style>
  #map {
    height: 400px;
    width: 100%;
  }
</style>


<br>


<div class="row">
  <div class="col-md-7">

<h5><%=@structure.name%> </h5 >
    <hr class="my-4">
    



<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @structure.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @structure.description %>
</p>

<p>
  <strong>Street:</strong>
  <%= @structure.street %>
</p>

<p>
  <strong>Street number:</strong>
  <%= @structure.street_number %>
</p>

<p>
  <strong>City:</strong>
  <%= @structure.city %>
</p>

<p>
  <strong>Province:</strong>
  <%= @structure.province %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @structure.zipcode %>
</p>

<p>
  <strong>Country:</strong>
  <%= @structure.country %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @structure.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @structure.longitude %>
</p>




<%= link_to 'Edit', edit_structure_path(@structure) %> |
<%= link_to 'Back', structures_path %>

</div>
  
<div class="col-md-4">
  
<h5>Mappa</h5 >
    <hr class="my-4">
 <div id="map"></div>
</div>

</div>

<script>
  function initMap() {
    var myLatLng = { lat: <%=@structure.latitude%>, lng: <%=@structure.longitude%>};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 16,
      center: myLatLng 
    });
    
      var marker = new google.maps.Marker({
      position: myLatLng,
         map: map
     });

        var content = "<%= @structure.name%>";
        var infowindow = new google.maps.InfoWindow();


        google.maps.event.addListener(marker,'click', (function(marker,content,infowindow){
        return function() {
           infowindow.setContent(content);
           infowindow.open(map,marker);
        };
        })(marker,content,infowindow));


    }
</script>
  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDi1llQEL98mof5OiynESOraX2piDuo_EM&callback=initMap">
    </script>