config/routes.rb
Rails.application.routes.draw do
  devise_for :users , controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}  
  
  namespace :admin do
   root  to: 'dashboard#index'
   resources :structures
  end
  
  namespace :api do
    namespace :v1 do
      resources :structures
      resources :posts
    end
  end


    
  get 'posts/index'

  get 'posts/show'

  get 'contacts/index'

  get 'about/index'

  get 'home/index'

  get 'account/index'

  get 'what_see/index'
  
  root "home#index"

  resources :posts do
    resources :comments
  end
  resources :structures, only: [:index, :show]



  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  validates :city, :province, :country, :street, :street_number, :zipcode, presence: true
  belongs_to :addressable, polymorphic: true 
  #after_validation :geocode  
  #geocoded_by :full_address

  #def full_address
  #  [street, street_number, zipcode, city, province, country].compact.join(' ')
  #end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: {message: 'campo obbligatorio'}
  has_many :comments
  belongs_to :user
  has_and_belongs_to_many :categories
  scope :published, -> {where(published: true)}
end

app/models/seo_tag.rb
class SeoTag < ApplicationRecord
  validates :tag_title, :tag_description, presence: true
  belongs_to :seo_polymorphic, polymorphic: true 
end

app/models/structure.rb
class Structure < ApplicationRecord
  validates :name, :description, presence: true

  has_one :address, :as => :addressable, inverse_of: :addressable
  accepts_nested_attributes_for :address, allow_destroy: true
  has_one :seo_tag, :as => :seo_polymorphic, inverse_of: :seo_polymorphic
  accepts_nested_attributes_for :seo_tag, allow_destroy: true
 end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  
  has_many :posts

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.first_name   # assuming the user model has a name
    user.last_name = auth.info.last_name
    user.image = auth.info.image # assuming the user model has an image
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    #user.skip_confirmation!
  end
end



end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @time = Time.now
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]


  def index
    @posts = Post.published.order('created_at DESC')
  end

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build
  end

  def edit
    @post = Post.find(params[:id]) 
  end 

 
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
  
   if @post.save
    redirect_to @post
   else
    render 'new'
   end

  end

  def update
   @post = Post.find(params[:id])
   if @post.update(post_params)
     redirect_to @post
   else
     render 'edit'
   end

  end

  def destroy
   @post = Post.find(params[:id])
   @post.destroy
   redirect_to posts_path
 
  end

 

   private
  
  def post_params
    params.require(:post).permit(:title, :body, :published, :meta_title, :meta_description, :user_id, {category_ids:[]})
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


  def full_title(page_title = '')
    base_title = "Gioiosando lo Smart Social Network"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def meta_descriptions(page_description = ' ')
    base_description = "Gioiosando - progetto Progetto #smartcity in ambito digitale creato da ASC Web Apps in collaborazione con Smart Gioiosa e la comunità di sviluppo web Sicily on Rails"
    if page_description.empty?
      #tag('meta', name: 'description', content: "#{base_description}")
      base_description
    else
      #tag('meta', name: 'description', content: "#{base_description} - #{page_description}")
       "#{base_description} - #{page_description}"
    end
  end



  def gravatar_for(user)
    if user.image
      image_tag("https://graph.facebook.com/#{user.uid}/picture?type=large")
    else
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
      image_tag(gravatar_url, alt: user.email)
    end
  end


  def gravatar_navbar(user)
     if user.image
      image_tag("https://graph.facebook.com/#{user.uid}/picture?type=small", width: "30", height: "30")
    else
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
      image_tag(gravatar_url, alt: user.email, width: "30", height: "30")
    end
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/structures_helper.rb
module StructuresHelper
end

app/helpers/what_see_helper.rb
module WhatSeeHelper
end

app/views/admin/shared/_footer.html.erb
<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; SmartGioiosa AscWebApps SicilyOnRails <%=Time.now.year%></p>
  </div>
  <!-- /.container -->
</footer>

app/views/admin/shared/_menu.html.erb
<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/admin">Gioiosando - Dashboard</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="about.html">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="services.html">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="services.html">Structures</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="contact.html">Contact</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Portfolio
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
            <a class="dropdown-item" href="portfolio-1-col.html">1 Column Portfolio</a>
            <a class="dropdown-item" href="portfolio-2-col.html">2 Column Portfolio</a>
            <a class="dropdown-item" href="portfolio-3-col.html">3 Column Portfolio</a>
            <a class="dropdown-item" href="portfolio-4-col.html">4 Column Portfolio</a>
            <a class="dropdown-item" href="portfolio-item.html">Single Portfolio Item</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Blog
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
            <a class="dropdown-item" href="blog-home-1.html">Blog Home 1</a>
            <a class="dropdown-item" href="blog-home-2.html">Blog Home 2</a>
            <a class="dropdown-item" href="blog-post.html">Blog Post</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Other Pages
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
            <a class="dropdown-item" href="full-width.html">Full Width Page</a>
            <a class="dropdown-item" href="sidebar.html">Sidebar Page</a>
            <a class="dropdown-item" href="faq.html">FAQ</a>
            <a class="dropdown-item" href="404.html">404</a>
            <a class="dropdown-item" href="pricing.html">Pricing Table</a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <title>Dashboard - Gioiosando</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 
  </head>

  <body>
    <%= render 'admin/shared/menu'%>
    <div class="container">      
      <%= yield%>
    </div>
    <%= render 'admin/shared/footer'%>
  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
       
    <title><%= full_title yield(:title)%></title>
    <meta name="description" content= "<%=meta_descriptions yield(:description)%>">
        
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-21109060-23"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-21109060-23');
  </script>


    <!-- Open Graph Facebook -->
  <%if controller.controller_name=="posts"%> 
    <meta property="og:url"                content="<%= request.original_url%>" />
    <meta property="og:type"               content="article" />
    <meta property="og:title"              content="<%= yield(:title)%>" />
    <meta property="og:description"        content="<%= yield(:description)%>" />
    <meta property="og:image"              content="<%= asset_url ("/assets/gioiosando.jpg")%>" />
  <%else%> 
    <meta property="og:url"                content="<%= request.original_url%>"/>
    <meta property="og:type"               content="article" />
    <meta property="og:title"              content="<%= full_title yield(:title)%>" />
    <meta property="og:description"        content="<%= meta_descriptions yield(:description)%>" />
    <meta property="og:image"              content="<%= asset_url ("/assets/gioiosando.jpg")%>" />
  <%end%>


  </head>

  <body>
    
<script>
  window.fbAsyncInit = function() {
    FB.init({ 
      <%if Rails.env.production?%>
        appId    : '<%= Rails.application.secrets.facebook_app_id %>',
      <%end%>
      appId      : '<%= Rails.application.secrets.facebook_app_id %>',
      cookie     : true,
      xfbml      : true,
      version    : 'v2.11'
    });
      
    FB.AppEvents.logPageView();   
      
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>


<!-- Navigation -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark  bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="/">Gioiosando</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <%= link_to "About", about_index_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Cosa Vedere", what_see_index_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Attività Commerciali", structures_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Contatti", contacts_index_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Posts", posts_path, class: "nav-link"%>
            </li>



            <% if user_signed_in? %>
                       
        <li class="nav-item dropdown">
         <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= gravatar_navbar current_user%>
            <%= current_user.email%>
        </a>
        
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Account", account_index_path,class: "dropdown-item"%>
          <%= link_to "Bacheca", "#", class: "dropdown-item"%>
          <div class="dropdown-divider"></div>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "dropdown-item") %>
        </div>
        </li>
         <% else %>
           <li class="nav-item">
            <%= link_to('Accedi', new_user_session_path, class: "nav-link")  %>
          </li>
    <% end %>


          






          </ul>
        </div>
      </div>
    </nav>















<div class="container">
  <%= yield %>
</div>


   <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; SmartGioiosa AscWebApps SicilyOnRails <%=Time.now.year%></p>
      </div>
      <!-- /.container -->
    </footer>

    
  </body>
</html>